documentation:
  - docs/**/*
  - README.md

examples:
  - examples/**/*

data:
  - src/flash/core/data/**/*

task:
  - src/flash/tabular/**/*
  - src/flash/text/**/*
  - src/flash/image/**/*
  - src/flash/video/**/*

tabular:
  - src/flash/tabular/**/*

text:
  - src/flash/text/**/*

vision:
  - src/flash/image/**/*
  - src/flash/video/**/*
