trigger:
  branches:
    include: ["master"]
pr:
  branches:
    include: ["master"]
  autoCancel: 'true'
  drafts: 'true'

jobs:
- template: template-examples.yml
  parameters:
    domains:
    - "image"
    - "text"
    - "tabular"
    - "video"
