trigger:
  branches:
    include: ["main"]
pr:
  branches:
    include: ["main"]
  autoCancel: true
  drafts: true

jobs:
- template: testing-template.yml
  parameters:
    configs:
    - "image"
    - "text"
    - "tabular"
