name: Check schema

on:
  push:
    branches: [master, "release/*"]
  pull_request:
    branches: [master, "release/*"]

jobs:
  check-schema:
    uses: Lightning-AI/utilities/.github/workflows/check-schema.yml@v0.7.1
    with:
      azure-dir: '.azure'

  check-package:
    uses: Lightning-AI/utilities/.github/workflows/check-package.yml@v0.7.1
    with:
      actions-ref: ${{ github.sha }}  # use local version
      artifact-name: dist-packages-${{ github.sha }}
      import-name: "flash"
