name: Check Code formatting

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  black:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Black Formatting
      uses: teddykoker/python-black-check@master
      with:
        line-length: '120'
