name: "Add Docs Link"

on: [status]

jobs:
  circleci_artifacts_redirector_job:
    runs-on: ubuntu-latest
    steps:
    - uses: larsoner/circleci-artifacts-redirector-action@master
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        artifact-path: 0/html/index.html
        circleci-jobs: build-Docs
