name: notebook-tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-20.04, macOS-10.15, windows-2019]
        python-version: [3.6, 3.8]
    env:
      TEST_ENV: TRUE
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U pip wheel;
        #pip install treon;
        pip install --requirement requirements/install.txt --pre --upgrade --quiet --find-links https://download.pytorch.org/whl/cpu/torch_stable.html;
        pip install --requirement requirements/test.txt --quiet --find-links https://download.pytorch.org/whl/torch_stable.html;
        pip install -r requirements/notebooks.txt --quiet --find-links https://download.pytorch.org/whl/torch_stable.html;
        pip install --no-deps .
    - name: Run Notebooks
      run: |
        #treon --threads=1 --exclude=notebooks/kaggle_tumor.ipynb # with more threads this requires to much RAM
        # ignore error code 5 (no tests)
        sh -c 'pytest notebooks/ ; ret=$?; [ $ret = 5 ] && exit 0 || exit $ret'

