name: NotebookTests

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-20.04, macOS-10.15, windows-2019]
        python-version: [3.6, 3.7, 3.8]
    env:
      TEST_ENV: TRUE
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U pip wheel;
        pip install treon;
        pip install -r requirements/install.txt;
        pip install -r requirements/tests.txt;
        pip install -r requirements/notebooks.txt;
        pip install --no-deps .
    - name: Run Notebooks
      run: |
        treon --threads=1 # with more threads this requires to much RAM
